version: '3'
 
services:
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql_con
        image: mariadb:10.2
        volumes:
            - db-data:/var/lib/mysql
            - ${PWD}/cartron.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}

    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        image: thecodingmachine/php:7.2-v2-apache
        volumes:
            - .:/var/www/html/:rw
            - ./var/logs/php:/usr/local/etc/logs
            - ./var/cache/composer:/var/www/.composer/cache
        links:
          - db:db
          - smtp:smtp
        environment:
            APACHE_DOCUMENT_ROOT: web/
            PHP_INI_ERROR_REPORTING: E_ALL & ~E_NOTICE
            APP_ENV: dev
            PHP_EXTENSION_INTL: 1
            PHP_INI_MEMORY_LIMIT: 2048M
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        user: ${LOCAL_USER}
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin_con
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - ${PHPMYADMIN_EXPOSED_PORT}:80
        links:
            - db:db
    smtp:
        container_name: ${COMPOSE_PROJECT_NAME}_smtp_con
        image: bornholm/fake-smtp
        ports:
            -  ${SMTP_EXPOSED_PORT}:2525
            -  ${FAKETOOLS_EXPOSED_PORT}:8080
        volumes:
            - ./var/smtp:/fake-smtp/data/smtp

volumes:
    db-data: {}
