<?php

namespace AppBundle\Repository;

/**
 * DegustationProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegustationProRepository extends \Doctrine\ORM\EntityRepository
{
}
