<?php

namespace AppBundle\Repository;

/**
 * DegustationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegustationRepository extends \Doctrine\ORM\EntityRepository
{
}
