<?php

namespace AppBundle\Repository;

/**
 * PageMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
