<?php

namespace AppBundle\Repository;

/**
 * SousMenuDegustationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousMenuDegustationRepository extends \Doctrine\ORM\EntityRepository
{
}
