<?php

namespace AppBundle\Repository;

/**
 * SousMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
