<?php

namespace AppBundle\Repository;

/**
 * SousMenuProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousMenuProduitsRepository extends \Doctrine\ORM\EntityRepository
{
}
