# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: email
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin_homepage
                failure_handler: AppBundle\Listener\AuthenticationFailListener
            logout:
                path: /logout
                target: /login
            logout_on_user_change: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/pro, roles: ROLE_USER }
