#!/bin/bash

set -e

cd "$(dirname $0)/.."

echo "==> Checking prerequisites…"
exit_code=0

if hash phpcs 2>/dev/null; then
    echo "PHP_CodeSniffer found: $(phpcs --version)"
else
    echo "PHP_CodeSniffer is required to run the project."
    exit_code=1
fi

do_update=
if [[ "$1" == "-u" ]]; then
    do_update=1
fi

echo "==> Setting up DB…"
unzip cartron.sql.zip

echo "==> Starting docker…"
docker-compose up -d

rm cartron.sql

echo "==> Installing Php dependencies…"
docker-compose exec php composer install

echo "==> Installing NPM dependencies…"
yarn install

echo "==> Update database schema…"
docker-compose exec php bin/console doctrine:schema:update --force

echo "==> Setup assets…"
docker-compose exec php bin/console assets:install web

exit $exit_code
