<?php

namespace Proxies\__CG__\Site\CartronBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Produits extends \Site\CartronBundle\Entity\Produits implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setTitreFr($titreFr)
    {
        $this->__load();
        return parent::setTitreFr($titreFr);
    }

    public function getTitreFr()
    {
        $this->__load();
        return parent::getTitreFr();
    }

    public function setDescriptionFr($descriptionFr)
    {
        $this->__load();
        return parent::setDescriptionFr($descriptionFr);
    }

    public function getDescriptionFr()
    {
        $this->__load();
        return parent::getDescriptionFr();
    }

    public function setTitreEn($titreEn)
    {
        $this->__load();
        return parent::setTitreEn($titreEn);
    }

    public function getTitreEn()
    {
        $this->__load();
        return parent::getTitreEn();
    }

    public function setDescriptionEn($descriptionEn)
    {
        $this->__load();
        return parent::setDescriptionEn($descriptionEn);
    }

    public function getDescriptionEn()
    {
        $this->__load();
        return parent::getDescriptionEn();
    }

    public function setFicheProduitFr($ficheProduitFr)
    {
        $this->__load();
        return parent::setFicheProduitFr($ficheProduitFr);
    }

    public function getFicheProduitFr()
    {
        $this->__load();
        return parent::getFicheProduitFr();
    }

    public function setFicheProduitEn($ficheProduitEn)
    {
        $this->__load();
        return parent::setFicheProduitEn($ficheProduitEn);
    }

    public function getFicheProduitEn()
    {
        $this->__load();
        return parent::getFicheProduitEn();
    }

    public function setPackshotJpgFr($packshotJpgFr)
    {
        $this->__load();
        return parent::setPackshotJpgFr($packshotJpgFr);
    }

    public function getPackshotJpgFr()
    {
        $this->__load();
        return parent::getPackshotJpgFr();
    }

    public function setPackshotJpgEn($packshotJpgEn)
    {
        $this->__load();
        return parent::setPackshotJpgEn($packshotJpgEn);
    }

    public function getPackshotJpgEn()
    {
        $this->__load();
        return parent::getPackshotJpgEn();
    }

    public function setPackshotPdfEn($packshotPdfEn)
    {
        $this->__load();
        return parent::setPackshotPdfEn($packshotPdfEn);
    }

    public function getPackshotPdfEn()
    {
        $this->__load();
        return parent::getPackshotPdfEn();
    }

    public function setPackshotPdfFr($packshotPdfFr)
    {
        $this->__load();
        return parent::setPackshotPdfFr($packshotPdfFr);
    }

    public function getPackshotPdfFr()
    {
        $this->__load();
        return parent::getPackshotPdfFr();
    }

    public function setPackshotEpsFr($packshotEpsFr)
    {
        $this->__load();
        return parent::setPackshotEpsFr($packshotEpsFr);
    }

    public function getPackshotEpsFr()
    {
        $this->__load();
        return parent::getPackshotEpsFr();
    }

    public function setPackshotEpsEn($packshotEpsEn)
    {
        $this->__load();
        return parent::setPackshotEpsEn($packshotEpsEn);
    }

    public function getPackshotEpsEn()
    {
        $this->__load();
        return parent::getPackshotEpsEn();
    }

    public function setFicheLogistiqueFr($ficheLogistiqueFr)
    {
        $this->__load();
        return parent::setFicheLogistiqueFr($ficheLogistiqueFr);
    }

    public function getFicheLogistiqueFr()
    {
        $this->__load();
        return parent::getFicheLogistiqueFr();
    }

    public function setFicheLogistiqueEn($ficheLogistiqueEn)
    {
        $this->__load();
        return parent::setFicheLogistiqueEn($ficheLogistiqueEn);
    }

    public function getFicheLogistiqueEn()
    {
        $this->__load();
        return parent::getFicheLogistiqueEn();
    }

    public function setMedailles1En($medailles1En)
    {
        $this->__load();
        return parent::setMedailles1En($medailles1En);
    }

    public function getMedailles1En()
    {
        $this->__load();
        return parent::getMedailles1En();
    }

    public function setMedailles1Fr($medailles1Fr)
    {
        $this->__load();
        return parent::setMedailles1Fr($medailles1Fr);
    }

    public function getMedailles1Fr()
    {
        $this->__load();
        return parent::getMedailles1Fr();
    }

    public function setMedailles2Fr($medailles2Fr)
    {
        $this->__load();
        return parent::setMedailles2Fr($medailles2Fr);
    }

    public function getMedailles2Fr()
    {
        $this->__load();
        return parent::getMedailles2Fr();
    }

    public function setMedailles2En($medailles2En)
    {
        $this->__load();
        return parent::setMedailles2En($medailles2En);
    }

    public function getMedailles2En()
    {
        $this->__load();
        return parent::getMedailles2En();
    }

    public function setMedailles3En($medailles3En)
    {
        $this->__load();
        return parent::setMedailles3En($medailles3En);
    }

    public function getMedailles3En()
    {
        $this->__load();
        return parent::getMedailles3En();
    }

    public function setMedailles3Fr($medailles3Fr)
    {
        $this->__load();
        return parent::setMedailles3Fr($medailles3Fr);
    }

    public function getMedailles3Fr()
    {
        $this->__load();
        return parent::getMedailles3Fr();
    }

    public function setMedailles4En($medailles4En)
    {
        $this->__load();
        return parent::setMedailles4En($medailles4En);
    }

    public function getMedailles4En()
    {
        $this->__load();
        return parent::getMedailles4En();
    }

    public function setMedailles4Fr($medailles4Fr)
    {
        $this->__load();
        return parent::setMedailles4Fr($medailles4Fr);
    }

    public function getMedailles4Fr()
    {
        $this->__load();
        return parent::getMedailles4Fr();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdDegustation(\Site\CartronBundle\Entity\DegustationPro $idDegustation = NULL)
    {
        $this->__load();
        return parent::setIdDegustation($idDegustation);
    }

    public function getIdDegustation()
    {
        $this->__load();
        return parent::getIdDegustation();
    }

    public function setIdSousMenu(\Site\CartronBundle\Entity\SousMenuProduits $idSousMenu = NULL)
    {
        $this->__load();
        return parent::setIdSousMenu($idSousMenu);
    }

    public function getIdSousMenu()
    {
        $this->__load();
        return parent::getIdSousMenu();
    }

    public function setImage($image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setRecetteFr($recetteFr)
    {
        $this->__load();
        return parent::setRecetteFr($recetteFr);
    }

    public function getRecetteFr()
    {
        $this->__load();
        return parent::getRecetteFr();
    }

    public function setRecetteEn($recetteEn)
    {
        $this->__load();
        return parent::setRecetteEn($recetteEn);
    }

    public function getRecetteEn()
    {
        $this->__load();
        return parent::getRecetteEn();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'titreFr', 'descriptionFr', 'titreEn', 'descriptionEn', 'ficheProduitFr', 'ficheProduitEn', 'packshotJpgFr', 'packshotJpgEn', 'packshotPdfEn', 'packshotPdfFr', 'packshotEpsFr', 'packshotEpsEn', 'ficheLogistiqueFr', 'ficheLogistiqueEn', 'medailles1En', 'medailles1Fr', 'medailles2Fr', 'medailles2En', 'medailles3En', 'medailles3Fr', 'medailles4En', 'medailles4Fr', 'recetteFr', 'recetteEn', 'image', 'id', 'idSousMenu', 'idDegustation');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}