<?php

namespace Proxies\__CG__\Site\CartronBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PageMenu extends \Site\CartronBundle\Entity\PageMenu implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setTitreFr($titreFr)
    {
        $this->__load();
        return parent::setTitreFr($titreFr);
    }

    public function getTitreFr()
    {
        $this->__load();
        return parent::getTitreFr();
    }

    public function setDescriptionFr($descriptionFr)
    {
        $this->__load();
        return parent::setDescriptionFr($descriptionFr);
    }

    public function getDescriptionFr()
    {
        $this->__load();
        return parent::getDescriptionFr();
    }

    public function setFicheFr($ficheFr)
    {
        $this->__load();
        return parent::setFicheFr($ficheFr);
    }

    public function getFicheFr()
    {
        $this->__load();
        return parent::getFicheFr();
    }

    public function setTitreEn($titreEn)
    {
        $this->__load();
        return parent::setTitreEn($titreEn);
    }

    public function getTitreEn()
    {
        $this->__load();
        return parent::getTitreEn();
    }

    public function setDescriptionEn($descriptionEn)
    {
        $this->__load();
        return parent::setDescriptionEn($descriptionEn);
    }

    public function getDescriptionEn()
    {
        $this->__load();
        return parent::getDescriptionEn();
    }

    public function setFicheEn($ficheEn)
    {
        $this->__load();
        return parent::setFicheEn($ficheEn);
    }

    public function getFicheEn()
    {
        $this->__load();
        return parent::getFicheEn();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdMenu(\Site\CartronBundle\Entity\Menu $idMenu = NULL)
    {
        $this->__load();
        return parent::setIdMenu($idMenu);
    }

    public function getIdMenu()
    {
        $this->__load();
        return parent::getIdMenu();
    }

    public function setLabelFr($labelFr)
    {
        $this->__load();
        return parent::setLabelFr($labelFr);
    }

    public function getLabelFr()
    {
        $this->__load();
        return parent::getLabelFr();
    }

    public function setLebleEn($lebleEn)
    {
        $this->__load();
        return parent::setLebleEn($lebleEn);
    }

    public function getLebleEn()
    {
        $this->__load();
        return parent::getLebleEn();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'titreFr', 'descriptionFr', 'ficheFr', 'titreEn', 'descriptionEn', 'ficheEn', 'labelFr', 'lebleEn', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}